---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    post:
      summary: Creates a car
      tags:
      - Cars
      parameters: []
      responses:
        '201':
          description: car created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                finance_fee:
                  type: integer
                purchase_fee:
                  type: integer
                total_amount:
                  type: integer
                duration:
                  type: integer
                apr:
                  type: decimal
                snapshot:
                  type: binary
              required:
              - name
              - description
          application/xml:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                finance_fee:
                  type: integer
                purchase_fee:
                  type: integer
                total_amount:
                  type: integer
                duration:
                  type: integer
                apr:
                  type: decimal
                snapshot:
                  type: binary
              required:
              - name
              - description
  "/api/v1/cars/{id}":
    get:
      summary: Retrieves a car
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: car found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  finance_fee:
                    type: integer
                  purchase_fee:
                    type: integer
                  total_amount:
                    type: integer
                  duration:
                    type: integer
                  apr:
                    type: decimal
                  snapshot:
                    type: binary
                required:
                - id
                - name
                - description
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  finance_fee:
                    type: integer
                  purchase_fee:
                    type: integer
                  total_amount:
                    type: integer
                  duration:
                    type: integer
                  apr:
                    type: decimal
                  snapshot:
                    type: binary
                required:
                - id
                - name
                - description
        '404':
          description: car not found
    delete:
      summary: Deletes a car
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: car deleted
        '404':
          description: car not found
  "/api/v1/reservations":
    post:
      summary: Creates a reservation
      tags:
      - Reservations
      parameters: []
      responses:
        '201':
          description: reservation created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: date
                city:
                  type: string
                user_id:
                  type: bigint
                car_id:
                  type: bigint
              required:
              - city
          application/xml:
            schema:
              type: object
              properties:
                date:
                  type: date
                city:
                  type: string
                user_id:
                  type: bigint
                car_id:
                  type: bigint
              required:
              - city
  "/api/v1/reservations/{id}":
    get:
      summary: Retrieves a reservation
      tags:
      - Reservations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: reservation found
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: date
                  city:
                    type: string
                  user_id:
                    type: bigint
                  car_id:
                    type: bigint
                required:
                - id
                - city
            application/xml:
              schema:
                type: object
                properties:
                  date:
                    type: date
                  city:
                    type: string
                  user_id:
                    type: bigint
                  car_id:
                    type: bigint
                required:
                - id
                - city
        '404':
          description: reservation not found
    delete:
      summary: Deletes a reservation
      tags:
      - Reservations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: reservation deleted
        '404':
          description: reservation not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
